### ISSUE TITLE
What's the name of the file icon theme (sorry if this sounds retarded)

### ISSUE THREAD

**Issue by MuhammadM1998** [praveenpuglia/tailwind-breeze#4]
Can anyone tell me the name of the file icon theme used in the theme snippets in vs code marketplace?

![image](https://preview.redd.it/mclow6rdyql81.png?width=3104&format=png&auto=webp&s=7a7fe76c892978cea0767c5b6052925881280778)

Sorry for the inconvenience, The theme is awesome I installed it and waiting for a dark version.

**Comment by praveenpuglia** [comment]
Hey! Not sure how I missed this but I think the icon theme used is https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons

Thanks for installing and using it. 

About dark theme, I personally can't look at dark theme since it gives me headaches. I'll be happy to take a PR that adds a dark version of it though.
